"""empty message

Revision ID: 61720cd1b58a
Revises: 468e68f4c49e
Create Date: 2023-04-06 13:53:41.796916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61720cd1b58a'
down_revision = '468e68f4c49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###
